import './Facilitators.css';

function Facilitate() {
    return (
        <div className="facilitate">
            <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
            <h1 className="Facilitate-title">Facilitators</h1>
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="Elizabeth Morgan"></img>
            <h2 className="Facilitate-nametag">Elizabeth Morgan</h2>
            <p className="BioBlurb">A proud Motherscholar and scholar activist, Elizabeth is a Candidate in Human Development at UC Davis. An educator by training, she holds a Master's in Education from the Harvard Graduate School of Education and has supported Early Childhood practitioners in utilizing developmentally appropriate practice and inclusion strategies since 2004. Elizabeth works as a program coordinator for the UC Davis Center for Excellence in Developmental Disabilities at the MIND Institute. Her area of focus includes Early Childhood and Early Intervention Services with a specific interest in under-represented populations. She's also an elected Board member for the Association for University Centers in Disabilities (AUCD) and Warmline Family Resource Center from her work as an ASD parent activist. When she isn't thinking about autism service equity, Elizabeth enjoys the theater, watching Netflix, and spending time with her family and their dog, Billie Jean.</p>
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="Jazmin Burns"></img>
            <h2 className="Facilitate-nametag">Jazmin Burns</h2>
            <p className="BioBlurb">In 2012, Dr. Burns began her work in the field of Psychology as an in-home Applied Behavioral Analysis (ABA) behavioral therapist, as well as serving as a Research Assistant (RA) at the UC Davis MIND Institute. Dr. Burns' love and passion for working with families with Neurodevelopmental Disabilities (NDDs) grew and she quickly realized she wanted to become a Clinical Psychologist. Dr. Burns graduated from UC Davis with her BA in English and minored in Psychology in 2013. After continuing to work at the MIND Institute for a couple of years, she attended Alliant International University, Sacramento and received her PsyD in Clinical Psychology in May 2019. Her work within UC Davis Health did not end during her schooling. She received a year of practicum training at the UC Davis CAARE Center where she was trained in Trauma-Focused Cognitive Behavioral Therapy (TF-CBT). It was during this training that Dr. Burns realized her passion for doing trauma-informed care. She completed a year of training at the Veterans' Administration (VA) in Mather, CA where she primarily worked in the PTSD Clinic doing trauma and neurodevelopmental assessments, co-facilitated substance abuse/PTSD support groups, as well as conducted Cognitive Processing Therapy (CPT) with veterans. Dr. Burns completed her internship at the Child and Adolescent Psychiatric Services (CAPS) clinic in Sacramento, CA and her postdoc at the UC Davis MIND Institute where she deepened her knowledge and experience working with children, adolescents, and young adults by co-facilitating social skills groups, administering psychological assessments, and conducting therapy. Additionally, Jazmin served as the Communications and Engagement Intern for the Association of University Centers on Disabilities (AUCD) and was recently selected by the CDC and AUCD as the newest Children's Mental Health Champion for California. Currently, Dr. Burns continues working at the MIND Institute, in addition to working at the group practice, Bridges of the Mind Psychological Services. In her free time, Dr. Burns enjoys travelling, cooking, eating, singing, watching movies/TV, playing video games, and spending time with her husband, family, friends, and three cats. Dr. Burns loves providing psychoeducational and psychological services to families to help them learn, grow, and prosper.</p>
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="Benita Shaw"></img>
            <h2 className="Facilitate-nametag">Benita Shaw</h2>
            <p className="BioBlurb">Benita is a proud mother of two young men. She has two Associate's of Arts Degree (one in Human Services and the other in Drug and Alcohol Counseling) and a Bachelor of Science Degree in Psychology and Ethics. Benita works as a Community Education Specialist at UC Davis MIND Institute in the Resource Center. She is a board member for Supported Life Institute, The Fly Brave Foundation, as well as the Disability Right Education and Defense Fund (DREDF). Benita serves on the advisory committee's for State Council on Developmental Disabilities, Alta Regional Center Self-Determination and Sacramento City Unified School District CAC. After many years of advocating for her son in 2017, she founded the GIFTS Foundation (Give Information and Support For Families to Triumph Successfully) which is a 501(c)3. Benita reminds herself everyday that with GOD all things are possible as long as she stays His course and keeps the Faith.</p>
        </div>
    )
}

export default Facilitate;